### ISSUE TITLE
Merge script config files

### ISSUE THREAD

**Issue by AlexanderNiedrig** [HeilemannLab/SPTAnalyser#5]
Instead of having a config file for every script, workflow could be improved by having a single config file that holds the information for all scripts which can be accessed if necessary.
As the folder structure is determined by our scripts already, the different input formats for the directories in the scripts do no matter, meaning it is only necessary to list the coverslips.
Furthermore it would be profitable to identify the current "level" of analysis per coverslip, allowing the list of directories to simply be expanded when new data is aquired instead of necessitating a new config for every batch of data.
This could be incorporated directly into the INPUT_DIRS parameter like: `dirname = status|path` for example `dir03 = 1|C:\Users\Example` where the 1 would indicate fully drawn rois, meaning the directory would only get recognized by the write_TS_macro
The config would then also need the following parameters: 

1. remove_str (the redundant string to be removed in the adapt_folder_structures)
2. background_roi 
3. intensity_range
4. macro_directory (all three for the write_TS_macro script)
5. The initial parameters for the displacement/pBleach converger or the write_swift_batch (tau, exp_displacement, max_displacement, max_displacement_pp,p_bleach,p_switch,diffraction_limit)

This could all be achieved with minimal changes to the individual scripts while retaining compability with the original config files.

**Comment by JohannaRahm** [comment]
we will keep the separate config files for now, as this makes it more flexible for the user to only use parts of the pipeline without the need to already determine all necessary parameters.
